### ISSUE TITLE
Julia 1.x?

### ISSUE THREAD

**Issue by robertdj** [oxinabox/TestReports.jl#4]
Hi

This package looks great for bringing test results to various build platforms. Do you plan to upgrade it to work with Julia 1.x?

**Comment by oxinabox** [comment]
Hmm. Good idea.
TBH,  I forgot I made this.

It would indeed be useful to bring it upto 1.x

I am unlikely to do it any time soon but I will accept and review PRs.

I think someone else might be maintaining an alternative.
Maybe @quinnj?
